sudo: required

language: python

dist: trusty

branches:
  only:
    - master
before_install:
  - sudo apt-get -qq update
  - pip install -r requirements.txt

python:
  - "2.7"

install: pip install $(cat requirements.txt)

script:
  - python app.py
