sudo: required

language: python

dist: trusty

branches:
  only:
    - master
    
before_install:
  - sudo apt-get -qq update

python:
  - "2.7"

install: pip install -r requirements.txt

before_script:
  - export FLASK_APP="$TRAVIS_BUILD_DIR/server.py"
  - export FLASK_DEBUG=1

script: flask test